# -*- coding: utf-8 -*-
"""Practica 3.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EeYzviiDkdanDbN-WHTQmMRmx9xQP0JG
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

df = pd.read_csv("/content/drive/MyDrive/Aquifer_Petrignano.csv")
display(df)

df.describe()

df.info()

gra=df.plot(figsize=(20,16), subplots=True)

df['Date'] = pd.to_datetime(df['Date'])
ndf=df.sort_values('Date')
ndf.head(10)

difer=ndf['Date'].diff()
equidistante = difer.nunique() == 1
print("¿Los datos son equidistantes en el tiempo?", equidistante)